### ISSUE TITLE
Add a bit of padding to each temrinal element

### ISSUE THREAD

**Issue by daonb** [afittestide/terminal7#20]
Add a css bit:
```css
.xterm { margin: 10px; }
```
Adds a bit of margin to the terminal text but confused the xtermjs's fit plugin which resulted in the having the last line hidden.
